export const MAX_SUBSCRIBER_TTL_SECONDS = 600; // 10 minutes
export const MAX_SUBSCRIBER_EXPIRY_TIME_MS = 10 * 1000 * 60; // 10 minutes
export const SUBSCRIBER_EXPIRY_CHECK_INTERVAL_MS = 1000 * 6; // 6 seconds

export const TOPIC_MESSAGES_TTL_SECONDS = MAX_SUBSCRIBER_TTL_SECONDS;
export const MAX_TOPIC_MESSAGES_LENGTH = 5000;
export const TOPIC_CONSUMER_ASSIGNMENT_POLL_INTERVAL_MS = 100;
export const TOPIC_CONSUMER_ASSIGNMENT_TIMEOUT_MS = 10 * 1000;
export const TOPIC_CONSUMER_UNHEALTHY_ASSIGNMENT_THRESHOLD = 3;
export const TOPIC_LEADER_LOCK_FENCE_MARGIN_MS = 1000;
export const TOPIC_CONSUMER_DISCONNECT_TIMEOUT_MS =
  TOPIC_LEADER_LOCK_FENCE_MARGIN_MS / 2;
export const TOPIC_LEADERSHIP_RELEASE_TIMEOUT_MS = 1000;
export const TOPIC_LEADER_LOCK_TTL_SECONDS = 6;
export const TOPIC_LEADER_LOCK_RENEW_INTERVAL_MS = 2 * 1000;
export const TOPIC_LEADER_READY_POLL_INTERVAL_MS = 100;
export const TOPIC_LEADER_READY_WAIT_TIMEOUT_MS =
  TOPIC_CONSUMER_ASSIGNMENT_TIMEOUT_MS + TOPIC_LEADER_LOCK_RENEW_INTERVAL_MS;
